//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

// 
// This code was auto-generated by Microsoft.VisualStudio.ServiceReference.Platforms, version 14.0.23107.0
// 
namespace InfopasazerApp.TrainsServiceReference {
    using System.Runtime.Serialization;
    
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="TrainGroup", Namespace="http://schemas.datacontract.org/2004/07/InfopasazerMiner")]
    public partial class TrainGroup : object, System.ComponentModel.INotifyPropertyChanged {
        
        private System.Collections.ObjectModel.ObservableCollection<InfopasazerApp.TrainsServiceReference.Train> ArrivalsField;
        
        private System.Collections.ObjectModel.ObservableCollection<InfopasazerApp.TrainsServiceReference.Train> DeparturesField;
        
        [System.Runtime.Serialization.DataMemberAttribute(Name="Arrivals@", IsRequired=true)]
        public System.Collections.ObjectModel.ObservableCollection<InfopasazerApp.TrainsServiceReference.Train> Arrivals {
            get {
                return this.ArrivalsField;
            }
            set {
                if ((object.ReferenceEquals(this.ArrivalsField, value) != true)) {
                    this.ArrivalsField = value;
                    this.RaisePropertyChanged("Arrivals");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(Name="Departures@", IsRequired=true)]
        public System.Collections.ObjectModel.ObservableCollection<InfopasazerApp.TrainsServiceReference.Train> Departures {
            get {
                return this.DeparturesField;
            }
            set {
                if ((object.ReferenceEquals(this.DeparturesField, value) != true)) {
                    this.DeparturesField = value;
                    this.RaisePropertyChanged("Departures");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="Train", Namespace="http://schemas.datacontract.org/2004/07/InfopasazerMiner")]
    public partial class Train : object, System.ComponentModel.INotifyPropertyChanged {
        
        private string CompanyUrlField;
        
        private string CompanyField;
        
        private string DateField;
        
        private string DelayField;
        
        private string DestinationField;
        
        private int IdField;
        
        private string NameField;
        
        private string PlannedTimeField;
        
        private string SourceField;
        
        [System.Runtime.Serialization.DataMemberAttribute(Name="CompanyUrl@", IsRequired=true)]
        public string CompanyUrl {
            get {
                return this.CompanyUrlField;
            }
            set {
                if ((object.ReferenceEquals(this.CompanyUrlField, value) != true)) {
                    this.CompanyUrlField = value;
                    this.RaisePropertyChanged("CompanyUrl");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(Name="Company@", IsRequired=true)]
        public string Company {
            get {
                return this.CompanyField;
            }
            set {
                if ((object.ReferenceEquals(this.CompanyField, value) != true)) {
                    this.CompanyField = value;
                    this.RaisePropertyChanged("Company");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(Name="Date@", IsRequired=true)]
        public string Date {
            get {
                return this.DateField;
            }
            set {
                if ((object.ReferenceEquals(this.DateField, value) != true)) {
                    this.DateField = value;
                    this.RaisePropertyChanged("Date");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(Name="Delay@", IsRequired=true)]
        public string Delay {
            get {
                return this.DelayField;
            }
            set {
                if ((object.ReferenceEquals(this.DelayField, value) != true)) {
                    this.DelayField = value;
                    this.RaisePropertyChanged("Delay");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(Name="Destination@", IsRequired=true)]
        public string Destination {
            get {
                return this.DestinationField;
            }
            set {
                if ((object.ReferenceEquals(this.DestinationField, value) != true)) {
                    this.DestinationField = value;
                    this.RaisePropertyChanged("Destination");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(Name="Id@", IsRequired=true)]
        public int Id {
            get {
                return this.IdField;
            }
            set {
                if ((this.IdField.Equals(value) != true)) {
                    this.IdField = value;
                    this.RaisePropertyChanged("Id");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(Name="Name@", IsRequired=true)]
        public string Name {
            get {
                return this.NameField;
            }
            set {
                if ((object.ReferenceEquals(this.NameField, value) != true)) {
                    this.NameField = value;
                    this.RaisePropertyChanged("Name");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(Name="PlannedTime@", IsRequired=true)]
        public string PlannedTime {
            get {
                return this.PlannedTimeField;
            }
            set {
                if ((object.ReferenceEquals(this.PlannedTimeField, value) != true)) {
                    this.PlannedTimeField = value;
                    this.RaisePropertyChanged("PlannedTime");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(Name="Source@", IsRequired=true)]
        public string Source {
            get {
                return this.SourceField;
            }
            set {
                if ((object.ReferenceEquals(this.SourceField, value) != true)) {
                    this.SourceField = value;
                    this.RaisePropertyChanged("Source");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(ConfigurationName="TrainsServiceReference.ITrains")]
    public interface ITrains {
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ITrains/Get", ReplyAction="http://tempuri.org/ITrains/GetResponse")]
        System.Threading.Tasks.Task<InfopasazerApp.TrainsServiceReference.TrainGroup> GetAsync(int stationId);
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface ITrainsChannel : InfopasazerApp.TrainsServiceReference.ITrains, System.ServiceModel.IClientChannel {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class TrainsClient : System.ServiceModel.ClientBase<InfopasazerApp.TrainsServiceReference.ITrains>, InfopasazerApp.TrainsServiceReference.ITrains {
        
        /// <summary>
        /// Implement this partial method to configure the service endpoint.
        /// </summary>
        /// <param name="serviceEndpoint">The endpoint to configure</param>
        /// <param name="clientCredentials">The client credentials</param>
        static partial void ConfigureEndpoint(System.ServiceModel.Description.ServiceEndpoint serviceEndpoint, System.ServiceModel.Description.ClientCredentials clientCredentials);
        
        public TrainsClient() : 
                base(TrainsClient.GetDefaultBinding(), TrainsClient.GetDefaultEndpointAddress()) {
            this.Endpoint.Name = EndpointConfiguration.BasicHttpBinding_ITrains.ToString();
            ConfigureEndpoint(this.Endpoint, this.ClientCredentials);
        }
        
        public TrainsClient(EndpointConfiguration endpointConfiguration) : 
                base(TrainsClient.GetBindingForEndpoint(endpointConfiguration), TrainsClient.GetEndpointAddress(endpointConfiguration)) {
            this.Endpoint.Name = endpointConfiguration.ToString();
            ConfigureEndpoint(this.Endpoint, this.ClientCredentials);
        }
        
        public TrainsClient(EndpointConfiguration endpointConfiguration, string remoteAddress) : 
                base(TrainsClient.GetBindingForEndpoint(endpointConfiguration), new System.ServiceModel.EndpointAddress(remoteAddress)) {
            this.Endpoint.Name = endpointConfiguration.ToString();
            ConfigureEndpoint(this.Endpoint, this.ClientCredentials);
        }
        
        public TrainsClient(EndpointConfiguration endpointConfiguration, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(TrainsClient.GetBindingForEndpoint(endpointConfiguration), remoteAddress) {
            this.Endpoint.Name = endpointConfiguration.ToString();
            ConfigureEndpoint(this.Endpoint, this.ClientCredentials);
        }
        
        public TrainsClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress) {
        }
        
        public System.Threading.Tasks.Task<InfopasazerApp.TrainsServiceReference.TrainGroup> GetAsync(int stationId) {
            return base.Channel.GetAsync(stationId);
        }
        
        public virtual System.Threading.Tasks.Task OpenAsync() {
            return System.Threading.Tasks.Task.Factory.FromAsync(((System.ServiceModel.ICommunicationObject)(this)).BeginOpen(null, null), new System.Action<System.IAsyncResult>(((System.ServiceModel.ICommunicationObject)(this)).EndOpen));
        }
        
        public virtual System.Threading.Tasks.Task CloseAsync() {
            return System.Threading.Tasks.Task.Factory.FromAsync(((System.ServiceModel.ICommunicationObject)(this)).BeginClose(null, null), new System.Action<System.IAsyncResult>(((System.ServiceModel.ICommunicationObject)(this)).EndClose));
        }
        
        private static System.ServiceModel.Channels.Binding GetBindingForEndpoint(EndpointConfiguration endpointConfiguration) {
            if ((endpointConfiguration == EndpointConfiguration.BasicHttpBinding_ITrains)) {
                System.ServiceModel.BasicHttpBinding result = new System.ServiceModel.BasicHttpBinding();
                result.MaxBufferSize = int.MaxValue;
                result.ReaderQuotas = System.Xml.XmlDictionaryReaderQuotas.Max;
                result.MaxReceivedMessageSize = int.MaxValue;
                result.AllowCookies = true;
                return result;
            }
            throw new System.InvalidOperationException(string.Format("Could not find endpoint with name \'{0}\'.", endpointConfiguration));
        }
        
        private static System.ServiceModel.EndpointAddress GetEndpointAddress(EndpointConfiguration endpointConfiguration) {
            if ((endpointConfiguration == EndpointConfiguration.BasicHttpBinding_ITrains)) {
                return new System.ServiceModel.EndpointAddress("http://localhost:8735/Trains.svc");
            }
            throw new System.InvalidOperationException(string.Format("Could not find endpoint with name \'{0}\'.", endpointConfiguration));
        }
        
        private static System.ServiceModel.Channels.Binding GetDefaultBinding() {
            return TrainsClient.GetBindingForEndpoint(EndpointConfiguration.BasicHttpBinding_ITrains);
        }
        
        private static System.ServiceModel.EndpointAddress GetDefaultEndpointAddress() {
            return TrainsClient.GetEndpointAddress(EndpointConfiguration.BasicHttpBinding_ITrains);
        }
        
        public enum EndpointConfiguration {
            
            BasicHttpBinding_ITrains,
        }
    }
}
